@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueApplicantList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueApplicantList
UniqueTagList -[hidden]down- UniqueApplicantList

UniqueTagList -right-> "*" Tag
UniqueApplicantList -right-> Applicant

Applicant -up-> "*" Tag

Applicant *--> Name
Applicant *--> Phone
Applicant *--> Email
Applicant *--> JobPosition
Applicant *--> Address
Applicant *--> Status
Applicant *--> Rating
Applicant *--> LocalDateTime
Applicant *--> String: profilePicturePath
@enduml
