@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ExportCommandParser" as ExportCommandParser LOGIC_COLOR
participant "e:ExportCommand" as ExportCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("export applicants.csv")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("export applicants.csv")
activate AddressBookParser

create ExportCommandParser
AddressBookParser -> ExportCommandParser
activate ExportCommandParser

ExportCommandParser --> AddressBookParser
deactivate ExportCommandParser

AddressBookParser -> ExportCommandParser : parse("applicants.csv")
activate ExportCommandParser

create ExportCommand
ExportCommandParser -> ExportCommand
activate ExportCommand

ExportCommand --> ExportCommandParser :
deactivate ExportCommand

ExportCommandParser --> AddressBookParser : e
deactivate ExportCommandParser
ExportCommandParser -[hidden]-> AddressBookParser
destroy ExportCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> ExportCommand : execute(m)
activate ExportCommand

ExportCommand -> Model : getFilteredPersonList()
activate Model

Model --> ExportCommand
deactivate Model

ExportCommand -> ExportUtil : writeToCsv("applicants.csv", list)
activate ExportUtil

ExportUtil --> ExportCommand
deactivate ExportUtil

create CommandResult
ExportCommand -> CommandResult
activate CommandResult

CommandResult --> ExportCommand
deactivate CommandResult

ExportCommand --> LogicManager : r
deactivate ExportCommand

[<-- LogicManager
deactivate LogicManager
@enduml
